### ISSUE TITLE
Publish epub/pdf

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/tr.javascript.info#186]
Hi,

I'd like to try publishing the epub/pdf, could you translate some phrases for that, please?
[tr.yml.zip](https://github.com/javascript-tutorial/tr.javascript.info/files/6120956/tr.yml.zip)

**Comment by bilgedemirkaya** [comment]
[tr.yml.txt](https://github.com/javascript-tutorial/tr.javascript.info/files/6192135/tr.yml.txt)

**Comment by iliakan** [comment]
Thank you!

BTW, is this correct:
```
not_translated: 'Bu materyal This madde henüz sadece: #{translatedLangs} dillerinde mevcuttur. Lütfen bize bu bölümün çevirisini <strong>#{currentLang.title}</strong> çevirmek <a href="#{url}">için yardım ediniz</a>.'
```

The word "This" in the middle is confusing.

**Comment by bilgedemirkaya** [comment]
It isn't correct. What is the original text?

**Comment by iliakan** [comment]
The last line here:
```
modern_javascript_tutorial: "Modern JavaScript Eğitimi"
subtitle: "Kolay konulardan daha zora doğru, basit fakat detaylı bir anlatım"
part: "#{num}. Bölüm"
more: "Devamı…"
contents: 'İçerik Tablosu'
description: "Ana eğitim iki bölümden oluşmaktadır. Bu bölümler JavaScript'i programlama dili olarak kapsamaktadır. Tarayıcı üzerinde çalışmaktadır. Bunun yanında konu ile ilgili makalelere de yer verilmiştir."

part3:
  title: "Ek Makaleler"
  content: "İlk iki bölümü bitirdiğinizi varsayarak bunlara ek konular üzerinden geçilmiştir. Burada herhangi bir sıra yoktur. İstediğiniz bölümü okuyabilirsiniz."

tutorial: Eğitim
tutorial_map: Eğitim haritası
not_translated: 'Bu materyal This madde henüz sadece: #{translatedLangs} dillerinde mevcuttur. Lütfen bize bu bölümün çevirisini <strong>#{currentLang.title}</strong> çevirmek <a href="#{url}">için yardım ediniz</a>.'
```

**Comment by iliakan** [comment]
The English variant:
```
modern_javascript_tutorial: "The Modern JavaScript Tutorial"
subtitle: "How it's done now. From the basics to advanced topics with simple, but detailed explanations."
part: "Part #{num}"
more: "More…"
contents: 'Table of contents'
description: 'Main course contains 2 parts which cover JavaScript as a programming language and working with a browser. There are also additional series of thematic articles.'

part3:
  title: "Additional articles"
  content: "List of extra topics that assume you've covered the first two parts of tutorial. There is no clear hierarchy here, you can read articles in the order you want."

tutorial: Tutorial
tutorial_map: Tutorial map
not_translated: 'This material is only available in the following languages: #{translatedLangs}. Please, <a href="#{url}">help us</a> translate into <strong>#{currentLang.title}</strong>.'
```
